# https://www.wemos.cc/en/latest/s2/s2_mini.html
substitutions:
  name: "wemos-s2-mini"
  friendly_name: "LOLIN Wemos S2 Mini"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  min_version: "2022.12.0"
  project:
    name: wemos_base.s2-mini
    version: "0.2"

esp32:
  board: lolin_s2_mini
  framework:
    # type: esp-idf  # ESP-IDF still doesn't compile on aarch64, REVIST
    type: arduino    # Use Arduino for better compatibility, at the cost of increased RAM use

wifi:
  ap: {}  # This spawns an AP with the device name and mac address with no password.

api:
logger:
ota:

dashboard_import:
  # Grab the latest version
  package_import_url: github://vidplace7/esphome-wemos/esp32-wemos-s2-mini.yaml

status_led:
  pin:
    number: GPIO15

button:
  - platform: safe_mode
    name: "${friendly_name} Safe Mode Boot"
    entity_category: diagnostic
