# https://www.wemos.cc/en/latest/c3/c3_mini.html
substitutions:
  name: "wemos-c3-mini"
  friendly_name: "LOLIN Wemos C3 Mini"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  min_version: "2022.11"  # Tested against '2022.11.5'
  project:
    name: wemos_base.c3-mini
    version: "0.1"
  platformio_options:               # Remove after 'lolin_c3_mini' supported properly - ESPHome 2022.12.0
    board_build.f_flash: 40000000L  # ''
    board_build.flash_mode: dio     # ''
    board_build.flash_size: 4MB     # ''
    board_build.variant: esp32c3    # ''

esp32:
  # board: lolin_c3_mini     # Enable after 'lolin_c3_mini' supported properly - ESPHome 2022.12.0
  board: esp32-c3-devkitm-1  # Remove after 'lolin_c3_mini' supported properly - ESPHome 2022.12.0
  variant: esp32c3           # ''
  framework:
    # type: esp-idf          # Enable after ESPHome 2022.12.0
    type: arduino            # Remove after ESPHome 2022.12.0
    version: 2.0.5           # ''
    platform_version: 5.2.0  # ''

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap: {}  # This spawns an AP with the device name and mac address with no password.

api:
logger:
ota:

dashboard_import:
  # Grab the latest version
  package_import_url: github://vidplace7/esphome-wemos/esp32-wemos-c3-mini.yaml

button:
  - platform: safe_mode
    name: "${friendly_name} Safe Mode Boot"
    entity_category: diagnostic
