# https://www.wemos.cc/en/latest/c3/c3_mini.html
substitutions:
  name: "wemos-c3-mini"
  friendly_name: "LOLIN Wemos C3 Mini"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  min_version: "2022.12.0"
  project:
    name: wemos_base.c3-mini
    version: "0.2"
  platformio_options:                  # See defaults at https://github.com/platformio/platform-espressif32/blob/v5.2.0/boards/lolin_c3_mini.json
    board_build.flash_mode: dio        # Override, defaults to 'qio'
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"  # Override, defaults to '-DARDUINO_USB_CDC_ON_BOOT=1' -- Fixes OTA issues

esp32:
  board: lolin_c3_mini
  framework:
    # type: esp-idf  # Enable once an IDF-compatible WS2812B library is implemented
    type: arduino    # NeoPixelBus Requires arduino... for now?


wifi:
  output_power: "8.5"  # Required on esp32c3
  ap: {}               # This spawns an AP with the device name and mac address with no password.

api:
logger:
ota:

dashboard_import:
  # Grab the latest version
  package_import_url: github://vidplace7/esphome-wemos/esp32-wemos-c3-mini.yaml

button:
  - platform: safe_mode
    name: "${friendly_name} Safe Mode Boot"
    entity_category: diagnostic

light:
  - platform: neopixelbus
    name: "${friendly_name} RGB Light"
    variant: WS2812
    pin: 7
    num_leds: 1
    gamma_correct: 1.1
