# https://www.wemos.cc/en/latest/s2/s2_mini.html
substitutions:
  name: "wemos-s2-mini"
  friendly_name: "LOLIN Wemos S2 Mini"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  min_version: "2022.12.0"
  project:
    name: wemos_base.s2-mini
    version: "0.4"

esp32:
  board: lolin_s2_mini
  framework:
    # type: arduino  # Revert to arduino if needed (many components do not support esp-idf)
    type: esp-idf    # Enable esp-idf by default

    # esp-idf doesn't compile on aarch64, 'toolchain-esp32s2ulp' must be updated/replaced
    # Fixed in 'develop' branch of 'platform-espressif32'
    platform_version: "https://github.com/platformio/platform-espressif32.git#develop"

    # esp-idf 4.4.3 is required by the new ULP toolchains, ESPHome defaults to 4.4.2
    version: 4.4.3

wifi:
  ap: {}  # This spawns an AP with the device name and mac address with no password.

api:
logger:
ota:

dashboard_import:
  # Grab the latest version
  package_import_url: github://vidplace7/esphome-wemos/esp32-wemos-s2-mini.yaml

button:
  - platform: safe_mode
    name: "${name} Safe Mode Boot"
    entity_category: diagnostic

status_led:
  pin:
    number: GPIO15
