name: CI-MultiArch

on:
  push:
  pull_request:

jobs:
  ci-multiarch:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - esp32-wemos-c3-mini.yaml
          - esp32-wemos-s2-mini.yaml
          - esp8266-wemos-d1-mini.yaml
        version:
          - beta
        platform:
          - linux/amd64
          - linux/arm64
          # - linux/arm/v7
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build ESPHome firmware to verify configuration
        uses: vidplace7/esphome-build-action@multiarch-testing
        with:
          yaml_file: ${{ matrix.file }}
          version: ${{ matrix.version }}
          platform: ${{ matrix.platform }}
